In [26]:
import pandas as pd
import numpy as np

In [27]:
X = pd.read_csv('X_task.csv')
Y = pd.read_csv('Y_task.csv')
Z = pd.read_csv('Z_task.csv', index_col='index')

In [28]:
X

Х1    Х2    Х3   Х4
0  0.22  15.3  1.50  134
1  0.38  14.2  1.80   93
2  0.45  16.8  1.55  126
3  0.28  18.2  1.18   90
4  0.45  19.0  1.35  139
5  0.53  18.2  1.43  113
6  0.29  14.3  1.29  104

In [29]:
Y

Х1    Х2    Х3   Х4
0  0.41  15.5  1.20  105
1  0.32  12.3  1.15   65
2  0.43  11.2  1.18   75
3  0.62  17.8  1.17  100
4  0.84  16.8  1.22  115
5  0.93  12.8  1.16   85
6  0.54  12.2  1.17   80

In [30]:
Z

Х1     Х2    Х3   Х4
index                       
z1     0.3  13.23  1.31  103
z2     1.3  19.30  1.28  107

In [31]:
def get_cov_matrix(df):
    m = df.values
    cols = m.shape[1]
    cov_matrix = np.zeros((cols,cols), dtype=np.float32)
    
    for i in range(cols):
        for j in range(cols):
            p1 = m[:, i]
            p2 = m[:, j]
            cov_matrix[i,j] = np.mean((p1 - np.mean(p1))*(p2 - np.mean(p2)))
    
    return cov_matrix

np.set_printoptions(suppress=True)
np.set_printoptions(precision=2)

Sx = get_cov_matrix(X)
Sy = get_cov_matrix(Y)

print('Sx:')
print(Sx)

print('Sy:')
print(Sy)
    

Sx:
[[  0.01   0.1    0.     0.36]
 [  0.1    3.38  -0.17   9.98]
 [  0.    -0.17   0.03   0.07]
 [  0.36   9.98   0.07 326.69]]
Sy:
[[  0.04   0.16   0.     1.68]
 [  0.16   5.7    0.03  34.2 ]
 [  0.     0.03   0.     0.31]
 [  1.68  34.2    0.31 274.49]]


In [32]:
S = 1/(len(X) + len(Y) - 2) * (len(X)*Sx + len(Y)*Sy)
print('S:')
print(S)

S:
[[  0.03   0.15   0.     1.19]
 [  0.15   5.3   -0.09  25.77]
 [  0.    -0.09   0.02   0.22]
 [  1.19  25.77   0.22 350.69]]


In [33]:
invS = np.linalg.inv(S)

np.set_printoptions(precision=5)
print('S⁻¹:')
print(invS)

S⁻¹:
[[38.45132 -0.99773 -9.48038 -0.05166]
 [-0.99773  0.37077  1.95427 -0.02506]
 [-9.48038  1.95427 59.69427 -0.14824]
 [-0.05166 -0.02506 -0.14824  0.00496]]


In [34]:
A = invS@(np.mean(X, axis=0)-np.mean(Y, axis=0))
print('A:')
print(A)

A:
[-14.45447   1.02758  18.96735   0.03283]


In [35]:
Ux = X.values@A
Uy = Y.values@A

print('Ux:')
print(Ux)
print('Uy:')
print(Uy)

Ux:
[45.39269 46.29367 44.29523 39.99118 43.18927 41.87457 38.38515]
Uy:
[36.20948 31.96043 30.13745 34.80429 32.0376  24.50333 29.54953]


In [36]:
Ux_mean = np.mean(Ux)
Uy_mean = np.mean(Uy)
print('U̅x = ', Ux_mean)
print('U̅y = ', Uy_mean)

U̅x =  42.77453796501548
U̅y =  31.314588162337866


In [37]:
C = (Ux_mean + Uy_mean)/2
print('C =', C)

C = 37.04456306367668


In [40]:
strs = ['належить до вибірки X', 'належить до вибірки Y']

U = Z.values @ A
for i in range(len(U)):
    Uz = U[i]
    
    if Uz < C:
        if Ux_mean < C:
            print(f'Uz{i} = {Uz} < {C} {strs[0]}' )
        else:
            print(f'Uz{i} = {Uz} < {C} {strs[1]}' )
    else:
        if Ux_mean > C:
            print(f'Uz{i} = {Uz} > {C} {strs[0]}' )
        else:
            print(f'Uz{i} = {Uz} > {C} {strs[1]}' )
        
    
    

Uz0 = 37.487608140490515 > 37.04456306367668 належить до вибірки X
Uz1 = 28.8328679886209 < 37.04456306367668 належить до вибірки Y
